[general]
data_dir = ../db/data
parallel_limit = 8
default_depth = 1
default_indexing = garag
default_query = garag
default_embedding_model = all-MiniLM-L6-v2

[security]
ssl_cert_path = 
ssl_key_path = 

[database]
username = postgres
password = root
host = 
port = 
database_name = postgres

[arangodb]
url = ...
username = ...
password = ...

[elastic]
url = ...

[neo4j]
url = ...
password = ...
db_name = ...

[llm_index]
provider = e.g. ollama
base_url = ...
api_key = ...
model_name = ...
options = {"temperature": 0}

[llm_query]
provider = e.g. ollama
base_url = ...
api_key = ...
model_name = ...
options = {"temperature": 0}
; ollama: "num_ctx": 8096 ; openai: "max_tokens": 8096
