[general]
data_dir = ../db/data
parallel_limit = 8
default_depth = 1
default_indexing = garag
default_query = garag
default_embedding_model = paraphrase-multilingual-MiniLM-L12-v2

[security]
ssl_cert_path = 
ssl_key_path = 

[database]
username = postgres
password = root
host = 
port = 
database_name = postgres

[arangodb]
url = http://127.0.0.1:8529/
username = root
password =

[elastic]
url = http://127.0.0.1:9200/

[llm_index]
provider = ollama
base_url = 
api_key =
model_name = llama3.1:8b
options = {"temperature": 0.1, "top_p": 0.99}

[llm_query]
provider = ollama
base_url = 
api_key = 
model_name = llama3.1:8b
options = {"temperature": 0.1, "top_p": 0.95}
; ollama: "num_ctx": 8096 ; openai: "max_tokens": 8096