[ERI_SETTINGS]
data_source_name = Internal Documents
data_source_description = Contains internal documents parsed into a graph database.
allowed_provider_type = ANY
authorization_methods = ["NONE"]
ssl_cert_path =
ssl_key_path =
postgres_connection = {
        "username": "postgres",
        "password": "",
        "url": "",
        "database_name": "eri_server"
    }

; [GARAG]
; config = {
;         "top_k": number of retrieved docuements,
;         "confidence_cutoff": e.g. 0.04,
;         "vector_db_index_name": DATABASE_NAME
;     }
; emb_model = EMBEDDING_MODEL
; elastic_db_url = ...
; arango_db = {
;         "url": ...,
;         "username": ...,
;         "password": ...,
;         "db_name": ...,
;         "graph_name": "community_graph"
;     }

; [GraphRAG]
; config = {
;         "top_k": number of retrieved docuements,
;         "confidence_cutoff": e.g. 40,
;         "community_degree": 1
;     }
; llm = {
;         "provider": e.g. "ollama",
;         "base_url": ...,
;         "api_key": ...,
;         "model_name": MOODEL_NAME,
;         "options": {}
;     }
; arango_db = {
;         "url": ...,
;         "username": ...,
;         "password": ...,
;         "db_name": ...,
;         "graph_name": ...
;     }

; [NaiveGraphRAG]
; config = {
;         "top_k": e.g. 1024,
;         "confidence_cutoff": e.g. 0.04,
;         "vector_db_index_name": ...
;     }
; emb_model = EMBEDDING_MODEL
; elastic_db_url = ...

; [NaiveRAG]
; config = {
;         "top_k": e.g. 1024,
;         "confidence_cutoff": e.g. 0.04,
;         "vector_db_index_name": ...
;     }
; emb_model = EMBEDDING_MODEL
; elastic_db_url = ...

[VectorGR]
config = {
        "top_k": ...,
        "v_index_name": "vector_index_all",
        "return_properties": [],
        "filters": {}
    }
emb_model = EMBEDDING_MODEL
llm = {
        "provider": e.g. "ollama",
        "base_url": ...,
        "api_key": ...,
        "model_name": ...,
        "options": {}
    }
neo4j_db = {
        "url": ...,
        "db_name": ...,
        "password": ...
    }  

[HybridGR]
config = {
        "top_k": e.g. 30,
        "v_index_name": ...,
        "f_index_name": ...,
        "return_properties": []
    }
emb_model = EMBEDDING_MODEL
llm = {
        "provider": e.g. "ollama",
        "base_url": ...,
        "api_key": ...,
        "model_name": ...,
        "options": {}
    }
neo4j_db = {
        "url": ...,
        "db_name": ...,
        "password": ...
    }  

[Text2Cypher]
config = {
        "examples": ["USER INPUT: 'Which actors starred in the Matrix?' QUERY: MATCH (p:Person)-[:ACTED_IN]->(m:Movie) WHERE m.title = 'The Matrix' RETURN p.name"]
    }
llm = {
        "provider": e.g. "ollama",
        "base_url": ...,
        "api_key": ...,
        "model_name": ...,
        "options": {}
    }
neo4j_db = {
        "url": ...,
        "db_name": ...,
        "password": ...
    }  
