[ERI_SETTINGS]
data_source_name = Internal Documents
data_source_description = Contains internal documents parsed into a graph database.
allowed_provider_type = SELF_HOSTED
authorization_methods = ["NONE"]
ssl_cert_path =
ssl_key_path =
postgres_connection = {
        "username": "postgres",
        "password": "",
        "url": "",
        "database_name": "eri_server"
    }

; [GARAG]
; config = {
;         "top_k": 1024,
;         "confidence_cutoff": 0.04,
;         "vector_db_index_name": "sc_pub_garag"
;     }
; emb_model = paraphrase-multilingual-MiniLM-L12-v2
; elastic_db_url = http://127.0.0.1:9200
; arango_db = {
;         "url": "http://127.0.0.1:8529",
;         "username": "root",
;         "password": "",
;         "db_name": "SC_Pub",
;         "graph_name": "community_graph"
;     }

; [GraphRAG]
; config = {
;         "top_k": 1024,
;         "confidence_cutoff": 40,
;         "community_degree": 1
;     }
; llm = {
;         "provider": "ollama",
;         "base_url": "http://127.0.0.1:11434",
;         "api_key": "",
;         "model_name": "llama3.2:latest",
;         "options": {}
;     }
; arango_db = {
;         "url": "http://127.0.0.1:8529",
;         "username": "root",
;         "password": "",
;         "db_name": "SC_Pub",
;         "graph_name": "community_graph"
;     }

; [NaiveGraphRAG]
; config = {
;         "top_k": 1024,
;         "confidence_cutoff": 0.04,
;         "vector_db_index_name": "sc_pub_garag"
;     }
; emb_model = paraphrase-multilingual-MiniLM-L12-v2
; elastic_db_url = http://127.0.0.1:9200

; [NaiveRAG]
; config = {
;         "top_k": 1024,
;         "confidence_cutoff": 0.04,
;         "vector_db_index_name": "sc_pub_rag"
;     }
; emb_model = paraphrase-multilingual-MiniLM-L12-v2
; elastic_db_url = http://127.0.0.1:9200

; [VectorGR]
; config = {
;         "top_k": 5,
;         "v_index_name": "",
;         "return_properties": [],
;         "filters": {}
;     }
; emb_model = paraphrase-multilingual-MiniLM-L12-v2
; llm = {
;         "provider": "ollama",
;         "base_url": "http://127.0.0.1:11434",
;         "api_key": "",
;         "model_name": "llama3.2:latest",
;         "options": {}
;     }
; neo4j_db = {
;         "url": "",
;         "db_name": "",
;         "password": ""
;     }

; [HybridGR]
; config = {
;         "top_k": 5,
;         "v_index_name": "",
;         "f_index_name": "",
;         "return_properties": []
;     }
; emb_model = paraphrase-multilingual-MiniLM-L12-v2
; llm = {
;         "provider": "ollama",
;         "base_url": "http://127.0.0.1:11434",
;         "api_key": "",
;         "model_name": "llama3.2:latest",
;         "options": {}
;     }
; neo4j_db = {
;         "url": "",
;         "db_name": "",
;         "password": ""
;     }

; [Text2Cypher]
; config = {
;         "examples": ""
;     }
; llm = {
;         "provider": "ollama",
;         "base_url": "http://127.0.0.1:11434",
;         "api_key": "",
;         "model_name": "llama3.2:latest",
;         "options": {}
;     }
; neo4j_db = {
;         "url": "",
;         "db_name": "",
;         "password": ""
;     }
