FROM python:3.10-slim-buster

VOLUME /tls

# Workdir
WORKDIR /app

# install requirements
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# Copy init scripts
COPY src/ src/
COPY scripts/Quickstart.py Quickstart.py

ENTRYPOINT ["python", "Quickstart.py"]
CMD []
